fix msvc build again (reapply 3a1d260c9, upstreamed as 0c7b82a2e; reverts 1364cf763)
C:/src/OSGeo4W/src/qgis-dev/qgis/external/pdal_wrench/utils.cpp(121): error C3493: 'CHUNK_SIZE' cannot be implicitly captured because no default capture mode has been specified