docker-qgis-clangtidy: Downgrade clang-tidy version to match ubuntu 24.04
At the moment the clang-tidy CI fails on each file with the following
message:

```
error: PCH file uses an older PCH format that is no longer supported
[clang-diagnostic-error]
```

This is because clang-tidy version 18 is used while QGIS
compilation is achieved with clang 15. Indeed, QGIS is built with
clazy support which relies on clang 15.

This issue is fixed by using clang version 15 instead of version 18 in
`docker-qgis-clangtidy.sh`.