qgssfcgalgeometry: Add a default copy assignment operator
This fixes the following compilation error:
```
definition of implicit copy assignment operator for
'QgsSfcgalGeometry' is deprecated because it has a user-provided copy
constructor [-Werror,-Wdeprecated-copy-with-user-provided-copy] 89 |
QgsSfcgalGeometry( const QgsSfcgalGeometry &otherGeom ) SIP_THROW(
QgsSfcgalException );
```